version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestLDSProject12345Project
  gitServerName: moaa
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM
  gitUsername: Mohamed-Naufal-A-IBM
  gitBranch: main
services:
- serviceName: project.testldsproject12345.integrations:test
  packages:
  - name: TestLDSProject12345Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2047
